# frozen_string_literal: true

namespace :coverage do
  desc 'Collates all result sets generated by the different test runners'
  task report: :environment do
    require 'simplecov'

    SimpleCov.collate Dir['coverage/backend-*/.resultset.json'] do
      coverage_dir "coverage/final-report-#{Time.now.to_i}"
    end
  end
end
