version: "2"
plugins:
  duplication:
    enabled: true
    config:
      languages:
      - ruby
      - javascript
  fixme:
    enabled: true
ratings:
  paths:
  - Gemfile.lock
  - "**.erb"
  - "**.rb"
  - "**.slim"
  - "**.coffee"
  - "**.js"
exclude_paths:
- bin/
- config/
- db/
- spec/
- lib/
