require: rubocop-rspec

Rails:
  Enabled: true

AllCops:
  UseCache: true
  CacheRootDirectory: ./tmp/**
  TargetRubyVersion: 2.5.1
  DisplayCopNames: true
  Exclude:
    - bin/**/*
    - db/**/*
    - vendor/**/*
    - lib/templates/**/*

Rails/HasAndBelongsToMany:
  Enabled: false

Rails/OutputSafety:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/RepeatedDescription:
  Enabled: false

RSpec/MessageSpies:
  EnforcedStyle: receive

Style/AndOr:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/MethodCalledOnDoEndBlock:
  Enabled: true

Style/CollectionMethods:
  Enabled: true

Style/SymbolArray:
  Enabled: true

Style/StringLiterals:
  EnforcedStyle: single_quotes
  ConsistentQuotesInMultiline: true

Style/EmptyMethod:
  EnforcedStyle: expanded
  SupportedStyles:
    - compact
    - expanded

Layout/AlignParameters:
  EnforcedStyle: with_fixed_indentation
  SupportedStyles:
    - with_first_parameter
    - with_fixed_indentation

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringMethods:
  Enabled: true

Metrics/LineLength:
  Max: 120

Metrics/BlockLength:
  Enabled: false

Layout/EndAlignment:
  EnforcedStyleAlignWith: variable
  SupportedStylesAlignWith:
    - keyword
    - variable
