version: 2.1
orbs:
  ruby: circleci/ruby@1.1.1

jobs:
  test:
    docker:
      - image: circleci/ruby:2.5.1-stretch-node
    executor: ruby/default
    steps:
      - checkout
      - ruby/install-deps
      - ruby/rspec-test
      - run:
          name: Run quality checks
          command: bin/quality

workflows:
  CD:
    jobs:
      - tests
